# Generated by Django 4.2.5 on 2023-09-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomization',
            name='is_stuff',
        ),
        migrations.AddField(
            model_name='usercustomization',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is staff'),
        ),
    ]
